### ISSUE TITLE
image size problems

### ISSUE THREAD

**Issue by MrBurnst** [BBillot/hypothalamus_seg#4]
Hi!

In both the (linux) binary and the repo version, I get an error about some tensor sizes:

```
Traceback (most recent call last):
  File "scripts/predict.py", line 25, in <module>
    predict(**args)
  File "hypothalamus_seg/predict.py", line 95, in predict
    sigma_smoothing)
  File "hypothalamus_seg/predict.py", line 312, in build_model
    input_model=net)
  File "ext/neuron/models.py", line 182, in unet
    input_model=enc_model)
  File "ext/neuron/models.py", line 513, in conv_dec
    last_tensor = KL.concatenate([cat_tensor, last_tensor], axis=ndims + 1, name=name)
  File "venv/lib/python3.6/site-packages/keras/layers/merge.py", line 649, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "venv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "venv/lib/python3.6/site-packages/keras/layers/merge.py", line 362, in build
    'Got inputs shapes: %s' % (input_shape))
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 256, 256, 256, 24), (None, 48, 256, 256, 480)]

```

thanks!

**Comment by BBillot** [comment]
sorry for the extremely late answer
I changed the code quite a bit since then (with a lot of tests), so it's likely not to be a problem anymore.
sorry again
